
spring:
  config:
    activate:
      on-profile: dev # 환경이름설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/artory?serverTimezone=Asia/Seoul
    url: 
    username:
    password: 
  jpa:
    hibernate:
      ddl-auto: update

    #    show-sql: true #??? sql ??
    properties:
      hibernate:
        format_sql: true #sql ??? ??
        default_batch_fetch_size: 500  #?? ? ??? ?? ???

    open-in-view: false # ??? ????? ?? ??? ???? ??? ??


kakao:
  client:
    id: 
    secret: 
  callback:
    url: 
naver:
  client:
    id: 
    secret: 
  callback:
    url: 
