server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /Users/seung-woo/Documents/UMC/BackEnd-1/src/main/java/com/example/demo/exteranal/s3Bucket/tempImages # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.type: trace # ???? ??? ????? ? ? ?? ?? ??
    com.app: debug # todo ??? ??

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


#kakao:
#  client:
#    id: ee35f9bdbb7d489738218a16bc693718
#    secret: WlH1pCtFLtTBJIACJW2aIh7azY3ZK47R
#naver:
#  client:
#    id: 4yrLNCK6RQMeFj95vayh
#    secret: mfAMbtRMFO
#  callback:
#    url: http://3.39.39.6:8080/login/oauth2/code/naver
cloud:
  aws:
    s3:
      bucket: artory-webserver
    credentials:
      access-key: AKIAWRCJKOKJW4IQCQR7
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

token:
  secret: ENC(9c9uJh1XDJMe72tcz8o94Z1pqQxRrUddasasdjkhlasfhasdjkasdKaxFAlScPFuIGZtp57tFR3Q==) # ??? ???
  access-token-expiration-time: 90000000  # 15? 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2? 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)