
spring:
  config:
    activate:
      on-profile: prod # 환경이름설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/artory?serverTimezone=Asia/Seoul
    url: jdbc:mysql://artory-db.ccjn8ih7e8h5.ap-northeast-2.rds.amazonaws.com:3306/artory?serverTimezone=Asia/Seoul
    username: ${dev_username}
    password: ${dev_password}
  jpa:
    hibernate:
      ddl-auto: update

    #    show-sql: true #??? sql ??
    properties:
      hibernate:
        format_sql: true #sql ??? ??
        default_batch_fetch_size: 500  #?? ? ??? ?? ???

    open-in-view: false # ??? ????? ?? ??? ???? ??? ??

client-ip: http://localhost:3000
kakao:
  client:
    id: ee35f9bdbb7d489738218a16bc693718
    secret: ${prod_kakao}
  callback:
    url: http://artory-prod-env.eba-axnhdqgn.ap-northeast-2.elasticbeanstalk.com/oauth/kakao/callback
naver:
  client:
    id: 27AEJS87AXoGop3MoHhW
    secret: ${prod_naver}
  callback:
    url: http://artory-prod-env.eba-axnhdqgn.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/naver
