
spring:
  config:
    activate:
      on-profile: dev # 환경이름설정

kakao:
  client:
    id: afaaa3a1b79e589ad64e93e6e8b08ef7
    secret: L0Kykc6Yaeey9ZWKQUDaSawgnP462jp4
  callback:
    url: http://localhost:8080/oauth/kakao/callback
naver:
  client:
    id: 4yrLNCK6RQMeFj95vayh
    secret: mfAMbtRMFO
  callback:
    url: http://localhost:8080/login/oauth2/code/naver