
spring:
  config:
    activate:
      on-profile: dev # 환경이름설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/artory?serverTimezone=Asia/Seoul
    url: ENC(0KwyJqsjTKo43hcb1Kmi5hZLE5aIbENSxKUUGP/06V82f64c/Z7VpVWZknqfbU0/7uobsrOeTuq7u73GGGOXv/dMA952GEV6elwakLZecPZRnL/AKhs4McGHa2dQl/EJVc+8iAg+VjQYT99HqCw+9Y7/ai5GDaQc)
    username: ENC(gbeoPOAw6gIr7jUx7c8Rjw==)
    password: ENC(sJV0A60WMDZO6EkaQqzoRDWBT4Rh98hM)

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
jasypt:
  encryptor:
    key: keytouseforencryption

    #    show-sql: true #??? sql ??
    properties:
      hibernate:
        format_sql: true #sql ??? ??
        default_batch_fetch_size: 500  #?? ? ??? ?? ???

    open-in-view: false # ??? ????? ?? ??? ???? ??? ??


kakao:
  client:
    id: afaaa3a1b79e589ad64e93e6e8b08ef7
    secret: L0Kykc6Yaeey9ZWKQUDaSawgnP462jp4
  callback:
    url: http://localhost:8080/oauth/kakao/callback
naver:
  client:
    id: 4yrLNCK6RQMeFj95vayh
    secret: mfAMbtRMFO
  callback:
    url: http://localhost:8080/login/oauth2/code/naver
