server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artory?serverTimezone=Asia/Seoul
    username: root
    password: 1108




  jpa:
    hibernate:
      ddl-auto: update

#    show-sql: true #??? sql ??
    properties:
      hibernate:
        format_sql: true #sql ??? ??
        default_batch_fetch_size: 500  #?? ? ??? ?? ???

    open-in-view: false # ??? ????? ?? ??? ???? ??? ??

  servlet:
    multipart:
      max-file-size: 1000MB #?? ??? ??? ??? ?? ??? 10MB ??? ???.
      max-request-size: 1000MB # ?? ??? ?? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.type: trace # ???? ??? ????? ? ? ?? ?? ??
    com.app: debug # todo ??? ??

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: ee35f9bdbb7d489738218a16bc693718
    secret: WlH1pCtFLtTBJIACJW2aIh7azY3ZK47R
naver:
  client:
    id: 4yrLNCK6RQMeFj95vayh
    secret: mfAMbtRMFO
  callback:
    url: http://localhost:8080/login/oauth2/code/naver


token:
  secret: ENC(9c9uJh1XDJMe72tcz8o94Z1pqQxRrUddasasdjkhlasfhasdjkasdKaxFAlScPFuIGZtp57tFR3Q==) # ??? ???
  access-token-expiration-time: 900000  # 15? 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2? 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)