name: Build and Test
on:
  pull_request:
    types: [closed]
  workflow_dispatch: # (2).수동 실행도 가능하도록
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod'
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with: 
          java-version: '17'
      - run: touch ./src/main/resources/jasypt.properties
      - run: echo "${{ secrets.JASYPT }}" > ./src/main/resources/jasyptproperties
      - run: cat ./src/main/resources/jasypt.properties
      # gradlew에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # gradlew 빌드
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
