name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with: 
          java-version: '17'
<<<<<<< HEAD
      - run: touch ./src/main/resources/application-secret.properties
      - run: echo "${{ secrets.JASYPT }}" > ./src/main/resources/application-secret.properties
      - run: cat ./src/main/resources/application-secret.properties
=======
      - run: touch ./src/main/resources/jasypt.properties
      - run: echo "${{ secrets.JASYPT }}" > ./src/main/resources/jasyptproperties
      - run: cat ./src/main/resources/jasypt.properties
>>>>>>> origin/wonjae/5
      # gradlew에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # gradlew 빌드
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
